server:
  port: 8770
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
  cloud:
    config:
      discovery:
        service-id: config-server #指定配置中心的服务名称
        enabled: true
      fail-fast: true
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://admin:123@localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}


fdfs:
  connect-timeout: 601
  so-timeout: 1501
  thumb-image: #缩略图
    width: 60
    height: 660
  tracker-list:  #tracker 地址
  - 192.168.176.128:22122