server:
  port: 8772

spring:
  datasource:
    url: jdbc:mysql://10.11.64.226:3306/hychina
    password: 1234
    username: user
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

feign:
  hystrix:
    enabled: true



